//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alldeli.BusinessLogic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.ProfileUsers = new HashSet<ProfileUser>();
            this.States = new HashSet<State>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Abreviation { get; set; }
    
        public virtual ICollection<ProfileUser> ProfileUsers { get; set; }
        public virtual ICollection<State> States { get; set; }
    }
}
