//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alldeli.BusinessLogic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryAddress
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int CityId { get; set; }
        public string ZipCode { get; set; }
        public string Street { get; set; }
        public string Number { get; set; }
        public string Departament { get; set; }
        public string StreetRef { get; set; }
        public string Instructions { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
