//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alldeli.BusinessLogic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsMenu
    {
        public ItemsMenu()
        {
            this.OrderDetailsItemMenus = new HashSet<OrderDetailsItemMenu>();
            this.ValuesItems = new HashSet<ValuesItem>();
        }
    
        public int Id { get; set; }
        public int IdMenu { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte OptionalTypeId { get; set; }
        public decimal Price { get; set; }
        public int OrderBy { get; set; }
        public byte CountOption { get; set; }
    
        public virtual OptionalType OptionalType { get; set; }
        public virtual ICollection<OrderDetailsItemMenu> OrderDetailsItemMenus { get; set; }
        public virtual ICollection<ValuesItem> ValuesItems { get; set; }
    }
}
