//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alldeli.BusinessLogic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionalType
    {
        public OptionalType()
        {
            this.ItemsMenus = new HashSet<ItemsMenu>();
        }
    
        public byte Id { get; set; }
        public string OptionType { get; set; }
        public bool Enabled { get; set; }
    
        public virtual ICollection<ItemsMenu> ItemsMenus { get; set; }
    }
}
