//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alldeli.BusinessLogic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetailsValue
    {
        public int Id { get; set; }
        public int OrderDetailItemMenuId { get; set; }
        public int ValueItemId { get; set; }
    
        public virtual OrderDetailsItemMenu OrderDetailsItemMenu { get; set; }
        public virtual ValuesItem ValuesItem { get; set; }
    }
}
