//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alldeli.BusinessLogic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.DeliveryAddresses = new HashSet<DeliveryAddress>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.OrderProfiles = new HashSet<OrderProfile>();
            this.Payments = new HashSet<Payment>();
            this.ShippingCosts = new HashSet<ShippingCost>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public byte StatusId { get; set; }
        public System.DateTime Date { get; set; }
        public string DeliveryTime { get; set; }
        public System.DateTime DeliveryDate { get; set; }
    
        public virtual ICollection<DeliveryAddress> DeliveryAddresses { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<OrderProfile> OrderProfiles { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<ShippingCost> ShippingCosts { get; set; }
    }
}
