//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alldeli.BusinessLogic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public Partner()
        {
            this.Categories = new HashSet<Category>();
            this.Menus = new HashSet<Menu>();
            this.PartnersSellers = new HashSet<PartnersSeller>();
            this.Restaurants = new HashSet<Restaurant>();
            this.Contacts = new HashSet<Contact>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ContactId { get; set; }
        public string name { get; set; }
        public string TaxId { get; set; }
        public bool Enabled { get; set; }
        public string Logo { get; set; }
        public string Description { get; set; }
        public decimal ShippingCost { get; set; }
        public decimal MinimumOrderAmount { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string CreatedUser { get; set; }
        public string UpdatedUser { get; set; }
    
        public virtual ICollection<Category> Categories { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual ICollection<Menu> Menus { get; set; }
        public virtual ICollection<PartnersSeller> PartnersSellers { get; set; }
        public virtual ICollection<Restaurant> Restaurants { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
    }
}
