//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alldeli.BusinessLogic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnersSeller
    {
        public int SellerId { get; set; }
        public int PartnerId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Partner Partner { get; set; }
        public virtual Seller Seller { get; set; }
    }
}
