//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alldeli.BusinessLogic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public decimal Amount { get; set; }
        public string CardNumbre { get; set; }
        public string SecurtyNumber { get; set; }
        public byte CardTypeId { get; set; }
        public string ProviderToken { get; set; }
        public byte StatusId { get; set; }
        public string FullNameTitular { get; set; }
        public System.DateTime ExpirationDate { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
