//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alldeli.BusinessLogic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public Phone()
        {
            this.Restaurants = new HashSet<Restaurant>();
        }
    
        public int Id { get; set; }
        public string Area { get; set; }
        public string Number { get; set; }
        public int TypeId { get; set; }
    
        public virtual PhoneType PhoneType { get; set; }
        public virtual ICollection<Restaurant> Restaurants { get; set; }
    }
}
