//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alldeli.BusinessLogic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public Restaurant()
        {
            this.OpeningHours = new HashSet<OpeningHour>();
            this.Phones = new HashSet<Phone>();
        }
    
        public int Id { get; set; }
        public int PartnerId { get; set; }
        public Nullable<int> PrincipalContact { get; set; }
        public string Name { get; set; }
        public int CityId { get; set; }
        public string StreetPrincipal { get; set; }
        public string StreetRef1 { get; set; }
        public string ZipCode { get; set; }
        public string CoorX { get; set; }
        public string CoorY { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string CreatedUser { get; set; }
        public string UpdatedUser { get; set; }
    
        public virtual ICollection<OpeningHour> OpeningHours { get; set; }
        public virtual Partner Partner { get; set; }
        public virtual ICollection<Phone> Phones { get; set; }
    }
}
