//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alldeli.BusinessLogic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValuesItem
    {
        public ValuesItem()
        {
            this.OrderDetailsValues = new HashSet<OrderDetailsValue>();
        }
    
        public int Id { get; set; }
        public int ItemMenuId { get; set; }
        public string Value { get; set; }
        public byte OrderBy { get; set; }
    
        public virtual ItemsMenu ItemsMenu { get; set; }
        public virtual ICollection<OrderDetailsValue> OrderDetailsValues { get; set; }
    }
}
